partial support for raspberry pi 5

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -408,8 +408,9 @@ elif [ "$ARCH" = "armv7l" ] ; then
    ARCH="armv6"
 elif [ "$ARCH" = "aarch64" ] ; then
    # Recent Rasp Pi 4
-   CPU_ARCH="armv6"
-   ARCH="armv6"
+   # was ARCH="armv6" but this is no longer valid
+   CPU_ARCH="armv9-a"
+   ARCH="armv9-a"
 else
    CPU_ARCH="$ARCH"
 fi
@@ -451,12 +452,22 @@ elif [ "$OS" = "Linux" -a "$CPU_ARCH" = "armv7" ] ; then
          exit 1
       fi
    fi
-   # Rasp Pi FAQ: these C flags should be used.  However, they must be applied
-   # to the entire application and I don't have a way to pass them to the
-   # third-party libraries.  However, I document them here.
-   #CFLAGSTYPE="-mfpu=vfp -mfloat-abi=hard"
-   # GCC Ada 4.6's Gnatmake crashes on GCC -m switches on cargs
-   #GMCARGSSUB="-mfpu=vfp -mfloat-abi=hard"
+
+# Raspberry Pi 5
+
+elif [ "$OS" = "Linux" -a "$CPU_ARCH" = "armv9-a" ] ; then
+   echo -n "Linux/ARM64 (assuming Raspberry Pi 5)"
+   if test -r spar_os.ads ; then
+      echo " (cached, make distclean to remove)";
+   else
+      echo
+      # The standard linux file works with the Pi
+      cp os_bindings/spar_linux.ads spar_os.ads
+      if [ $? -ne 0 ] ; then
+         echo "Unable to find appropriate spar_os source files"
+         exit 1
+      fi
+   fi
 elif [ "$OS" = "Linux" -a "$CPU_ARCH" = "i386" ] ; then
    echo -n "Linux/Intel/AMD"
    if test -r spar_os.ads ; then
